language: python

python:
  - "3.6.7"

services:
  - postgres

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create database test_ireporter;" -U postgres
  - psql -c "create user developer with password 'developer';" -U postgres

env:
  - HOST=localhost POSTGRESPORT=5432 TEST_DATABASE_NAME=test_ireporter USER=developer PASSWORD=developer

script:
  - py.test --cov=app tests/

after_success:
  - coveralls
